### ISSUE TITLE
Not an issue, but somewhere to post test results.

### ISSUE THREAD

**Issue by iains** [iains/gcc-13-branch#1]

**Comment by iains** [comment]
**GCC-13.3-darwin-r0**

**Arm64 (macOS 12)**

[summ-aarch64-darwin21-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414469/summ-aarch64-darwin21-r13-8870.txt)

**X86_64**

[summ-x86_64-darwin23-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414480/summ-x86_64-darwin23-r13-8870.txt)

[summ-x86_64-darwin21-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414483/summ-x86_64-darwin21-r13-8870.txt)

[summ-x86_64-darwin21-r13-8870-rosetta.txt](https://github.com/iains/gcc-13-branch/files/15414487/summ-x86_64-darwin21-r13-8870-rosetta.txt)

[summ-x86_64-darwin20-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414490/summ-x86_64-darwin20-r13-8870.txt)

[summ-x86_64-darwin19-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414493/summ-x86_64-darwin19-r13-8870.txt)

[summ-x86_64-darwin18-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414494/summ-x86_64-darwin18-r13-8870.txt)

[summ-x86_64-darwin17-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414497/summ-x86_64-darwin17-r13-8870.txt)

[summ-x86_64-darwin16-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414499/summ-x86_64-darwin16-r13-8870.txt)

[summ-x86_64-darwin15-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15416503/summ-x86_64-darwin15-r13-8870.txt)

[summ-x86_64-darwin14-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15416803/summ-x86_64-darwin14-r13-8870.txt)

[summ-x86_64-darwin13-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15416507/summ-x86_64-darwin13-r13-8870.txt)

[summ-x86_64-darwin12-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15416515/summ-x86_64-darwin12-r13-8870.txt)

[summ-x86_64-darwin11-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15416519/summ-x86_64-darwin11-r13-8870.txt)

[summ-x86_64-darwin10-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15421971/summ-x86_64-darwin10-r13-8870.txt)

**i686**

[summ-i686-darwin17-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414514/summ-i686-darwin17-r13-8870.txt)

[summ-i686-darwin9-r13-8870.txt](https://github.com/iains/gcc-13-branch/files/15414515/summ-i686-darwin9-r13-8870.txt)

**PowerPC**

(not available, at present, but the RC1 passed)

**Comment by iains** [comment]
**GCC-13.3-darwin-r0**

**Arm64 (macOS 12)**

[summ-aarch64-darwin21-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15552436/summ-aarch64-darwin21-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

**X86_64**

[summ-x86_64-darwin23-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545237/summ-x86_64-darwin23-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin21-rosetta-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545241/summ-x86_64-darwin21-rosetta-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin21-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545246/summ-x86_64-darwin21-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin20-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545247/summ-x86_64-darwin20-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin19-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545250/summ-x86_64-darwin19-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin18-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545255/summ-x86_64-darwin18-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin17-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545258/summ-x86_64-darwin17-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin16-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545263/summ-x86_64-darwin16-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin15-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545268/summ-x86_64-darwin15-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin14-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545270/summ-x86_64-darwin14-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin13-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545274/summ-x86_64-darwin13-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin12-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545278/summ-x86_64-darwin12-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-x86_64-darwin11-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545280/summ-x86_64-darwin11-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)



**i686**

[summ-i686-darwin17-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545281/summ-i686-darwin17-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

[summ-i686-darwin9-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt](https://github.com/user-attachments/files/15545293/summ-i686-darwin9-gcc-13-3-darwin-8872-gcc-13.3-darwin-r1.txt)

**PowerPC**

(not available, at present)

**Comment by ilg-ul** [comment]
I would like to give it a try, but I don't know what commits should I add to the Homebrew patches, the only recent commit I can find is a README update.

**Comment by iains** [comment]
> I would like to give it a try, but I don't know what commits should I add to the Homebrew patches, the only recent commit I can find is a README update.

https://github.com/iains/gcc-13-branch/commit/9fd551b97ef434170c0303dd2fa428727bd2e614 is the relevant commit.

Hmmmm.. let me check this, something appears to have gone wrong.

**Comment by iains** [comment]
hmm now I am confused - that patch _is_ in the 13.3-darwin-r0 release .. so it should be (AFAIK) in the Homebrew kit - @fxcoudert ? [so the r1 is actually unnecessary :( .. ]

please could you try just building the 13.3-darwin-r{0,1} branch and check if your issue is resolved - I cannot realistically check more than the trees I produce.

**Comment by ilg-ul** [comment]
> 9fd551b is the relevant commit.

Perhaps I'm missing something, but this commit seems to change only some comments:

```
diff --git a/fixincludes/fixincl.x b/fixincludes/fixincl.x
index 266c76df1d3..3749d8b7b3e 100644
--- a/fixincludes/fixincl.x
+++ b/fixincludes/fixincl.x
@@ -2,11 +2,11 @@
  *
  * DO NOT EDIT THIS FILE   (fixincl.x)
  *
- * It has been AutoGen-ed  May 22, 2024 at 10:16:02 AM by AutoGen 5.18.7
+ * It has been AutoGen-ed  June  1, 2024 at 05:24:18 PM by AutoGen 5.18.7
  * From the definitions    inclhack.def
  * and the template file   fixincl
  */
-/* DO NOT SVN-MERGE THIS FILE, EITHER Wed May 22 10:16:02 BST 2024
+/* DO NOT SVN-MERGE THIS FILE, EITHER Sat Jun  1 17:24:18 BST 2024
  *
  * You must regenerate it.  Use the ./genfixes script.
  *
-- 
2.39.3 (Apple Git-146)
```

**Comment by iains** [comment]
> > [9fd551b](https://github.com/iains/gcc-13-branch/commit/9fd551b97ef434170c0303dd2fa428727bd2e614) is the relevant commit.
> 
> Perhaps I'm missing something, but this commit seems to change only some comments:
> 
> ```
> diff --git a/fixincludes/fixincl.x b/fixincludes/fixincl.x
> index 266c76df1d3..3749d8b7b3e 100644
> --- a/fixincludes/fixincl.x
> +++ b/fixincludes/fixincl.x
> @@ -2,11 +2,11 @@
>   *
>   * DO NOT EDIT THIS FILE   (fixincl.x)
>   *
> - * It has been AutoGen-ed  May 22, 2024 at 10:16:02 AM by AutoGen 5.18.7
> + * It has been AutoGen-ed  June  1, 2024 at 05:24:18 PM by AutoGen 5.18.7
>   * From the definitions    inclhack.def
>   * and the template file   fixincl
>   */
> -/* DO NOT SVN-MERGE THIS FILE, EITHER Wed May 22 10:16:02 BST 2024
> +/* DO NOT SVN-MERGE THIS FILE, EITHER Sat Jun  1 17:24:18 BST 2024
>   *
>   * You must regenerate it.  Use the ./genfixes script.
>   *
> -- 
> 2.39.3 (Apple Git-146)
> ```

correct - because the patch had already been applied as : https://github.com/iains/gcc-13-branch/commit/8543cc246add9547bc9f80901dfc08ac7c1b64a7

So that all the reapplication did was to update the generation date info.

So - 13.3-darwin-r0 contains this fix; (as does 13.3-darwin-r1) therefore, please build  one of those trees and confirm (or not) that your problem is fixed.

**Comment by ilg-ul** [comment]
> So - 13.3-darwin-r0 contains this fix

The [gcc@13.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/g/gcc@13.rb) file includes a link to:

- https://raw.githubusercontent.com/Homebrew/formula-patches/bda0faddfbfb392e7b9c9101056b2c5ab2500508/gcc/gcc-13.3.0.diff

I searched for `fixincl.x` in that file and there is only one occurrence which is not a diff file name, so it seems that the file is not fixed in Homebrew.

**Comment by fxcoudert** [comment]
@ilg-ul the fix is not in Homebrew so far. Homebrew builds binaries for each macOS version (and matching SDK) separately, so the issue is not as problematic for us as it can be for a single binary distribution targeting multiple macOS versions.

Iain has linked the commit that you need to apply.

**Comment by ilg-ul** [comment]
So the Homebrew patch is **not** based on the `13.3-darwin-r0` tag?

**Comment by iains** [comment]
> So the Homebrew patch is **not** based on the `13.3-darwin-r0` tag?

"based on" != "identical" I think - HB omits the testsuite changes, for example.

**Comment by fxcoudert** [comment]
> So the Homebrew patch is not based on the 13.3-darwin-r0 tag?

It is based on the pre-release, which is almost the same, but did not include the fixincludes removal. I plan to include that eventually, and am testing it on GCC 14 first: https://github.com/Homebrew/homebrew-core/pull/173647

And yes, based on != identical. Each distributor (Homebrew like others) makes choices for distribution, based on their needs and constraints.

**Comment by ilg-ul** [comment]
I see, I assumed that the HB patches use exactly the commits tagged by Iain, like `13.3-darwin-r0`.

I prepared a patch like this:

```sh
git diff origin/gcc-13-3..fa196a8618c62428a372fb251f9fa292d4f275c2
```

(the numeric commit sha will eventually become `13.3-darwin-r1`)

Apart from the testsuite commits which are not relevant to me, are there any other commits that you exclude when preparing the patch for the HB distribution?

I'm trying to identify a way to create these patches in order to remain functionally compatible with the HB releases.

**Comment by ilg-ul** [comment]
With the updated patch the problem related to the availability macros seems fixed.

There is only one test failing in certain conditions, both for 14.a and 13.3, I'll prepare a separate issue for it.

**Comment by iains** [comment]
**GCC-13-4-darwin-r0**

**aarch64**

[summ-aarch64-darwin23-r13-9837.txt](https://github.com/user-attachments/files/20727721/summ-aarch64-darwin23-r13-9837.txt)
[summ-aarch64-darwin21-r13-9837.txt](https://github.com/user-attachments/files/20727722/summ-aarch64-darwin21-r13-9837.txt)


**x86_64**

[summ-x86_64-darwin24-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727684/summ-x86_64-darwin24-gcc-13-4-darwin-9837.txt)
[summ-x86_64-darwin23-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727685/summ-x86_64-darwin23-gcc-13-4-darwin-9837.txt)
[summ-x86_64-darwin21-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727687/summ-x86_64-darwin21-gcc-13-4-darwin-9837.txt)
[summ-x86_64-darwin21-gcc-13-4-darwin-9837-rosetta.txt](https://github.com/user-attachments/files/20727690/summ-x86_64-darwin21-gcc-13-4-darwin-9837-rosetta.txt)
[summ-x86_64-darwin20-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727692/summ-x86_64-darwin20-gcc-13-4-darwin-9837.txt)
[summ-x86_64-darwin19-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727695/summ-x86_64-darwin19-gcc-13-4-darwin-9837.txt)
[summ-x86_64-darwin18-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727697/summ-x86_64-darwin18-gcc-13-4-darwin-9837.txt)
[summ-x86_64-darwin17-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727698/summ-x86_64-darwin17-gcc-13-4-darwin-9837.txt)
[summ-x86_64-darwin16-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727700/summ-x86_64-darwin16-gcc-13-4-darwin-9837.txt)

**i686**

[summ-i686-darwin17-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727732/summ-i686-darwin17-gcc-13-4-darwin-9837.txt)
[summ-i686-darwin9-gcc-13-4-darwin-9837.txt](https://github.com/user-attachments/files/20727734/summ-i686-darwin9-gcc-13-4-darwin-9837.txt)
